remote_theme: pmarsceill/just-the-docs

exclude: ["Part1-NER/", "report.html"]

title: Data Science
search_enabled: true

aux_links:
  "View GitHub Repository":
    - "https://github.com/Rohit--Sharma/CS839_DataScience"
